version: "3"

services:
  gitea:
    image: gitea/gitea
    environment:
      - USER_UID=${USERID}
      - USER_GID=${GROUPID}
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mysql80:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=root
      - GITEA__database__PASSWD=root
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - mysql80
